### ISSUE TITLE
when will the source code released?

### ISSUE THREAD

**Issue by freesouls** [CompVis/adaptive-style-transfer#1]
Thanks for your great work in advance! @dimakot55 

When will you release the source code to public? After ECCV conference closed?

**Comment by dimakot55** [comment]
We will upload the code with pretrained models next week(hopefully on monday), datasets for training may take a bit longer.

**Comment by freesouls** [comment]
thanks for your reply!

**Comment by Redoykhan555** [comment]
@dimakot55, I failed to get a very simple point about the paper. So this paper produces one model per style, like Johnson et el, and not arbitrary style transfer like AdaIN, right? 
Thanks.

**Comment by asanakoy** [comment]
@Redoykhan555 Currently you need to train one model per style.
