### ISSUE TITLE
How to I make bigger pictures work on smaller gpus?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [CompVis/adaptive-style-transfer#13]
Given my gpu memory is too small to output images bigger than about 640 pixels, I tried splitting and reassembling a bigger image. Yet this doesn't work seamlessly and there is overall color variation. Which makes a nice effect, but how to I make bigger pictures work ie

1. by using split images
2. by using one big image

?

**Comment by asanakoy** [comment]
Use CPU instead of GPU. To enable CPU you should set `CUDA_VISIBLE_DEVICES=""`
```
CUDA_VISIBLE_DEVICES="" python main.py \
                 --model_name=model_van-gogh \
                 --phase=inference \
                 --image_size=1280 \
                 --ii_dir ../my_photographs1/,../my_photographs2/ \
                 --save_dir=../save_processed_images_here/

```
