### ISSUE TITLE
Multiple GPU training not working on AWS instances

### ISSUE THREAD

**Issue by miolamio** [CompVis/adaptive-style-transfer#20]
Hi guys, thank you for sharing this fantastic project! I'm using AWS g3 instance for training with 2 x Tesla M60 cards, looks like the training is not utilizing both cards at the same time.

Arguments: 
`CUDA_VISIBLE_DEVICES=0,1 python main.py --model_name=model_van-gogh --phase=inference --image_size=1280 --ii_dir=./samples/ --save_dir=./output/`

One of the cards is 100% utilized while the other one remains unused.

<img width="562" alt="documen 2018-12-19 16-46-16" src="https://user-images.githubusercontent.com/408235/50235552-33919700-03c9-11e9-8195-1bf481ea487e.png">

**Comment by asanakoy** [comment]
Hi,

It makes total sense, since the code is written for a single GPU. Setting more than one visible device with `CUDA_VISIBLE_DEVICES` will not affect anything.
