### ISSUE TITLE
Problem when inference with the model converted to pb

### ISSUE THREAD

**Issue by MaTJ89** [CompVis/adaptive-style-transfer#37]
Hi, I find this project very interesting, so I hope to deploy this on web (non-commercial use) for people to have fun with this.
After I convert the model to pb, the inference doesn't work. It shows **Input 0 of node encoder/g_e0_bn/scale/Assign_1 was passed float from encoder/g_e0_bn/scale_1:0 incompatible with expected float_ref**

I don't know much about tensorflow, or AI. I'm not sure if I did this persistence right.
Appreciating for anyone that could help.

**Comment by asanakoy** [comment]
HI,

Thanks for the interest! I'm very excited to see your web-app!

I'm not sure abot your error. But maybe you have to convert your input tensor to float32.
We could help you even more if you provided some minimal code example to reproduce your erorr.

**Comment by MaTJ89** [comment]
Never mind, I figure it out. It turns out that I used a placeholder with wrong type as input.
