### ISSUE TITLE
About the style image grouping.

### ISSUE THREAD

**Issue by NNNNAI** [CompVis/adaptive-style-transfer#38]
In the paper, you have mentioned a VGG16 network C used for Style Image Grouping.Is the pretrained model available？Many thanks.

**Comment by 13462877152** [comment]
Hello, I am also interested in the style image grouping . Have you solved it ?  How to choose some pictures with different style as much as possible?

**Comment by asanakoy** [comment]
Hi, the pretrained model is not available yet. I don't have a concrete plan to release it now, however, I may release it in the next few months.

**Comment by 13462877152** [comment]
Thank you very much for your reply. I  want to select images with different style as much as possible, such as different color.  I am puzzled about this problems

**Comment by asanakoy** [comment]
Hey. Sorry, I completely forgot, that the model was actually available all the time. If you go to https://github.com/CompVis/adaptive-style-transfer/tree/master/evaluation and download all the evaluation data by running https://github.com/CompVis/adaptive-style-transfer/blob/master/evaluation/download_evaluation_data.py - there will be also the model weights. And also the code to run the evaluation.

**Comment by NNNNAI** [comment]
Thanks for your help !~
