### ISSUE TITLE
Still runnable in Colab?

### ISSUE THREAD

**Issue by galabyca** [CompVis/adaptive-style-transfer#42]
I'm not able to run it on Colab. 

**From the command**
!CUDA_VISIBLE_DEVICES=0 python main.py \
                 --model_name=model_pollock \
                 --phase=inference \
                 --image_size=512 \
                 --ii_dir=./seed0168.png \
                 --save_dir=./out

**I'm getting**
[...]

Start inference.
 [*] Reading latest checkpoint from folder ./models/model_pollock/checkpoint.
 [*] Reading latest checkpoint from folder ./models/model_pollock/checkpoint_long.
Load checkpoint model10_pollock_bks10_flw100_300000.ckpt-300000. Initial step: 300000.
INFO:tensorflow:Restoring parameters from ./models/model_pollock/checkpoint_long/model10_pollock_bks10_flw100_300000.ckpt-300000
I1031 15:09:23.577128 140008567285632 saver.py:1284] Restoring parameters from ./models/model_pollock/checkpoint_long/model10_pollock_bks10_flw100_300000.ckpt-300000
 [*] Load SUCCESS
0it [00:00, ?it/s]
Inference is finished.

Here is the [Colab Notebook](https://colab.research.google.com/drive/11Ns0nZSW_QBowRsKdx_C7YGQuN2P2Kse?usp=sharing)

**Comment by m990130** [comment]
Hey, I think you should specify the folder containing all the content images path in `--ii_dir` instead of the image itself.
