### ISSUE TITLE
Links appear to be down

### ISSUE THREAD

**Issue by kjpoli** [CompVis/adaptive-style-transfer#43]
Just wanted to post in case this is still maintained, the links to the hcicloud download for the pertained models, style images and datasets all look down. I checked on two browsers and a direct wget with connection timing out.

**Comment by asanakoy** [comment]
Thanks for writing. Of course, it is maintained!

We moved the files to Google drive. Please refer to https://drive.google.com/drive/folders/1zsoLXTbMfQ-Of15jSA4uX-7FkzgiYmgw?usp=sharing 
We will update the links in the source code soon.

**Comment by dimakot55** [comment]
All the links are updated now.
