### ISSUE TITLE
Any plan for releasing the pre-trained model for calculating style transfer deception rate?

### ISSUE THREAD

**Issue by ycjing** [CompVis/adaptive-style-transfer#5]
Hi. Thanks for the nice code. The results are really impressive. It would be great if you could release the pre-trained model for calculating style transfer deception rate and follow-up works could thus have a quantitative comparison with your algorithm. Thanks!

**Comment by asanakoy** [comment]
Hi,
Yes, we will try to release it next week.

пт, 21 сен 2018 г., 14:52 Yongcheng Jing <notifications@github.com>:

**Comment by Redoykhan555** [comment]
I need the same model, but for style grouping mainly. @asanakoy, it'd be great help to have it sooner. If not possible, do you know any other publicly available model that did the same?

Thanks.

**Comment by asanakoy** [comment]
The instructions how to calculate deception score is now in [evaluation](evaluation) folder.

Run [evaluation/download_evaluation_data.py](evaluation/download_evaluation_data.py) to download a pretrained  model for deception rate computation or get it by the link https://yadi.sk/d/A2CBqSGuJ0M_XA.

I'm sorry for the delay.
