### ISSUE TITLE
Prediction Works, but Training Fails at Startup

### ISSUE THREAD

**Issue by Jaliborc** [CompVis/adaptive-style-transfer#6]
Hi. I am trying to run your example commands from the README file and the prediction is working perfectly. Yet, when I attempt to run your training example, the script crashes at startup:

> Traceback (most recent call last):                                                                                        File "main.py", line 149, in <module>                                                                                     tf.app.run()                                                                                                          File "C:\Users\j-cardoso\AppData\Local\Continuum\anaconda2\envs\Python 3.6\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run                                                                                                 _sys.exit(main(argv))                                                                                                 File "main.py", line 129, in main                                                                                         model = Artgan(sess, args)                                                                                            File "C:\Users\j-cardoso\Documents\adaptive-style-transfer\model.py", line 68, in __init__                                self._build_model()                                                                                                   File "C:\Users\j-cardoso\Documents\adaptive-style-transfer\model.py", line 133, in _build_model                           tf.add_n(self.input_photo_discr_loss.values()) + \                                                                    File "C:\Users\j-cardoso\AppData\Local\Continuum\anaconda2\envs\Python 3.6\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2118, in add_n                                                                                              raise ValueError("inputs must be a list of at least one Tensor with the "                                           ValueError: inputs must be a list of at least one Tensor with the same dtype and shape    

Any idea why this is happening? I downloaded the van-gogh image set and the places365_standard database.

**Comment by asanakoy** [comment]
Yes, our source code is for python 2.*.

**Comment by HenriAW** [comment]
Hi I had the same error and it was because I was using python 3 (same error on Windows and Linux). TensorFlow with Python 2 is not supported on Windows, so I'm running it inside a docker container at the moment which is working!

**Comment by asanakoy** [comment]
I'm closing this. Please use Python 2.7 and Tensorflow  1.2.

**Comment by HenriAW** [comment]
I managed to get the training working by using [this](http://www.pythonconverter.com/) website to convert the file model.py. Working ok now, although training is taking a while. Out of interest, what hardware was used for training the current models, and how long did it take?
