### ISSUE TITLE
When will video feature work?

### ISSUE THREAD

**Issue by Alexlander** [CompVis/adaptive-style-transfer#7]
Don't know if I'm allowed to make an issue out of this but I'd like to know if the video feature will work anytime soon, if there is anything (simple) I can help with I'd be glad to!

**Comment by asanakoy** [comment]
You can easily implement it yourself. Just process each frame of the video independently and then stitch everything back to a video.
If you want to make a pull request - you are welcome!

**Comment by Alexlander** [comment]
Ah ok :) 
I doubt it will look smooth, probably need to add an optical flow, but I'll try the stitching first!

**Comment by asanakoy** [comment]
We didn't use any temporal smoothing in the paper. Each frame was processed independently.

**Comment by Alexlander** [comment]
I could try to implement this: https://medium.com/element-ai-research-lab/stabilizing-neural-style-transfer-for-video-62675e203e42 B
But the stabilization will be implemented at training time.

I think it would be nicer to do it during the stitching of the frames with optical flow described here:
https://link.springer.com/article/10.1007%2Fs11263-018-1089-z
used in https://github.com/manuelruder/fast-artistic-videos

The first option could technically degrade the image quality when you only stylize a photo and the second option could degrade the quality of a video, but because the video is running anyway it's probably less worse if I go the optical flow route.

**Comment by edeetee** [comment]
Trying to do this kinda thing for a uni project. When I get it working I'll see if I can make it pushable :)

**Comment by asanakoy** [comment]
Yes, Munch is not just "Scream". It's a collection with "Scream" as a query image.

**Comment by asanakoy** [comment]
I have added steps to generate video in README .
