### ISSUE TITLE
Training seems to collapse after 38,000 iterations

### ISSUE THREAD

**Issue by alejodosr** [CompVis/adaptive-style-transfer#9]
Hi all,

First of all I want o congratulate you for your amazing work on style transfer :) I am currently training with your code in order to be able to generate semi-realistic images from simulated ones.

I am training with a Nvidia Tesla K80, and I see the following after certain iterations:

![step_36500](https://user-images.githubusercontent.com/3659632/47042582-ed7f4380-d18b-11e8-9749-e9ccb15b52aa.jpg)
Iteration 36500

![step_37000](https://user-images.githubusercontent.com/3659632/47042602-fa039c00-d18b-11e8-8337-5146bc0093eb.jpg)
Iteration 37000

![step_37500](https://user-images.githubusercontent.com/3659632/47042609-fff97d00-d18b-11e8-96e4-8ce3c37240b8.jpg)
Iteration 37500

![step_38000](https://user-images.githubusercontent.com/3659632/47042619-07208b00-d18c-11e8-92a3-665a4a5f5e19.jpg)
Iteration 38000

![step_38500](https://user-images.githubusercontent.com/3659632/47042626-0b4ca880-d18c-11e8-8f88-e80b959baaa3.jpg)
Iteration 38500

Is this normal? Do you have any suggestion? It worth mention that I am filling the Places2 dataset with my own data (only in the folder /a/abbey). Thanks in advance.

**Comment by dimakot55** [comment]
Well, that might be even the case for some models trained for style transfer task, it's a rare occasion still. Just try to continue training from the last checkpoint saved before model collapse. 
I shall add that we haven't tried to train the model for different datasets types like yours. Would be nice to hear some positive feedback.

**Comment by asanakoy** [comment]
closed due to inactivity
